begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one  *  or more contributor license agreements.  See the NOTICE file  *  distributed with this work for additional information  *  regarding copyright ownership.  The ASF licenses this file  *  to you under the Apache License, Version 2.0 (the  *  "License"); you may not use this file except in compliance  *  with the License.  You may obtain a copy of the License at  *  *       http://www.apache.org/licenses/LICENSE-2.0  *  *  Unless required by applicable law or agreed to in writing, software  *  distributed under the License is distributed on an "AS IS" BASIS,  *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  *  See the License for the specific language governing permissions and  *  limitations under the License.  */
end_comment

begin_package
DECL|package|org.apache.hadoop.fs.contract
package|package
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|fs
operator|.
name|contract
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|fs
operator|.
name|FSDataOutputStream
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|fs
operator|.
name|FileAlreadyExistsException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|fs
operator|.
name|FileStatus
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|fs
operator|.
name|FileSystem
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|fs
operator|.
name|Path
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Test
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|internal
operator|.
name|AssumptionViolatedException
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|FileNotFoundException
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|fs
operator|.
name|contract
operator|.
name|ContractTestUtils
operator|.
name|dataset
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|fs
operator|.
name|contract
operator|.
name|ContractTestUtils
operator|.
name|getFileStatusEventually
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|fs
operator|.
name|contract
operator|.
name|ContractTestUtils
operator|.
name|skip
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|fs
operator|.
name|contract
operator|.
name|ContractTestUtils
operator|.
name|touch
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|fs
operator|.
name|contract
operator|.
name|ContractTestUtils
operator|.
name|writeDataset
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|fs
operator|.
name|contract
operator|.
name|ContractTestUtils
operator|.
name|writeTextFile
import|;
end_import

begin_comment
comment|/**  * Test creating files, overwrite options etc.  */
end_comment

begin_class
DECL|class|AbstractContractCreateTest
specifier|public
specifier|abstract
class|class
name|AbstractContractCreateTest
extends|extends
name|AbstractFSContractTestBase
block|{
comment|/**    * How long to wait for a path to become visible.    */
DECL|field|CREATE_TIMEOUT
specifier|public
specifier|static
specifier|final
name|int
name|CREATE_TIMEOUT
init|=
literal|15000
decl_stmt|;
DECL|method|path (String filepath, boolean useBuilder)
specifier|protected
name|Path
name|path
parameter_list|(
name|String
name|filepath
parameter_list|,
name|boolean
name|useBuilder
parameter_list|)
throws|throws
name|IOException
block|{
return|return
name|super
operator|.
name|path
argument_list|(
name|filepath
operator|+
operator|(
name|useBuilder
condition|?
literal|""
else|:
literal|"-builder"
operator|)
argument_list|)
return|;
block|}
DECL|method|testCreateNewFile (boolean useBuilder)
specifier|private
name|void
name|testCreateNewFile
parameter_list|(
name|boolean
name|useBuilder
parameter_list|)
throws|throws
name|Throwable
block|{
name|describe
argument_list|(
literal|"Foundational 'create a file' test, using builder API="
operator|+
name|useBuilder
argument_list|)
expr_stmt|;
name|Path
name|path
init|=
name|path
argument_list|(
literal|"testCreateNewFile"
argument_list|,
name|useBuilder
argument_list|)
decl_stmt|;
name|byte
index|[]
name|data
init|=
name|dataset
argument_list|(
literal|256
argument_list|,
literal|'a'
argument_list|,
literal|'z'
argument_list|)
decl_stmt|;
name|writeDataset
argument_list|(
name|getFileSystem
argument_list|()
argument_list|,
name|path
argument_list|,
name|data
argument_list|,
name|data
operator|.
name|length
argument_list|,
literal|1024
operator|*
literal|1024
argument_list|,
literal|false
argument_list|,
name|useBuilder
argument_list|)
expr_stmt|;
name|ContractTestUtils
operator|.
name|verifyFileContents
argument_list|(
name|getFileSystem
argument_list|()
argument_list|,
name|path
argument_list|,
name|data
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
DECL|method|testCreateNewFile ()
specifier|public
name|void
name|testCreateNewFile
parameter_list|()
throws|throws
name|Throwable
block|{
name|testCreateNewFile
argument_list|(
literal|true
argument_list|)
expr_stmt|;
name|testCreateNewFile
argument_list|(
literal|false
argument_list|)
expr_stmt|;
block|}
DECL|method|testCreateFileOverExistingFileNoOverwrite (boolean useBuilder)
specifier|private
name|void
name|testCreateFileOverExistingFileNoOverwrite
parameter_list|(
name|boolean
name|useBuilder
parameter_list|)
throws|throws
name|Throwable
block|{
name|describe
argument_list|(
literal|"Verify overwriting an existing file fails, using builder API="
operator|+
name|useBuilder
argument_list|)
expr_stmt|;
name|Path
name|path
init|=
name|path
argument_list|(
literal|"testCreateFileOverExistingFileNoOverwrite"
argument_list|,
name|useBuilder
argument_list|)
decl_stmt|;
name|byte
index|[]
name|data
init|=
name|dataset
argument_list|(
literal|256
argument_list|,
literal|'a'
argument_list|,
literal|'z'
argument_list|)
decl_stmt|;
name|writeDataset
argument_list|(
name|getFileSystem
argument_list|()
argument_list|,
name|path
argument_list|,
name|data
argument_list|,
name|data
operator|.
name|length
argument_list|,
literal|1024
argument_list|,
literal|false
argument_list|)
expr_stmt|;
name|byte
index|[]
name|data2
init|=
name|dataset
argument_list|(
literal|10
operator|*
literal|1024
argument_list|,
literal|'A'
argument_list|,
literal|'Z'
argument_list|)
decl_stmt|;
try|try
block|{
name|writeDataset
argument_list|(
name|getFileSystem
argument_list|()
argument_list|,
name|path
argument_list|,
name|data2
argument_list|,
name|data2
operator|.
name|length
argument_list|,
literal|1024
argument_list|,
literal|false
argument_list|,
name|useBuilder
argument_list|)
expr_stmt|;
name|fail
argument_list|(
literal|"writing without overwrite unexpectedly succeeded"
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|FileAlreadyExistsException
name|expected
parameter_list|)
block|{
comment|//expected
name|handleExpectedException
argument_list|(
name|expected
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|IOException
name|relaxed
parameter_list|)
block|{
name|handleRelaxedException
argument_list|(
literal|"Creating a file over a file with overwrite==false"
argument_list|,
literal|"FileAlreadyExistsException"
argument_list|,
name|relaxed
argument_list|)
expr_stmt|;
block|}
block|}
annotation|@
name|Test
DECL|method|testCreateFileOverExistingFileNoOverwrite ()
specifier|public
name|void
name|testCreateFileOverExistingFileNoOverwrite
parameter_list|()
throws|throws
name|Throwable
block|{
name|testCreateFileOverExistingFileNoOverwrite
argument_list|(
literal|false
argument_list|)
expr_stmt|;
name|testCreateFileOverExistingFileNoOverwrite
argument_list|(
literal|true
argument_list|)
expr_stmt|;
block|}
DECL|method|testOverwriteExistingFile (boolean useBuilder)
specifier|private
name|void
name|testOverwriteExistingFile
parameter_list|(
name|boolean
name|useBuilder
parameter_list|)
throws|throws
name|Throwable
block|{
name|describe
argument_list|(
literal|"Overwrite an existing file and verify the new data is there, "
operator|+
literal|"use builder API="
operator|+
name|useBuilder
argument_list|)
expr_stmt|;
name|Path
name|path
init|=
name|path
argument_list|(
literal|"testOverwriteExistingFile"
argument_list|,
name|useBuilder
argument_list|)
decl_stmt|;
name|byte
index|[]
name|data
init|=
name|dataset
argument_list|(
literal|256
argument_list|,
literal|'a'
argument_list|,
literal|'z'
argument_list|)
decl_stmt|;
name|writeDataset
argument_list|(
name|getFileSystem
argument_list|()
argument_list|,
name|path
argument_list|,
name|data
argument_list|,
name|data
operator|.
name|length
argument_list|,
literal|1024
argument_list|,
literal|false
argument_list|,
name|useBuilder
argument_list|)
expr_stmt|;
name|ContractTestUtils
operator|.
name|verifyFileContents
argument_list|(
name|getFileSystem
argument_list|()
argument_list|,
name|path
argument_list|,
name|data
argument_list|)
expr_stmt|;
name|byte
index|[]
name|data2
init|=
name|dataset
argument_list|(
literal|10
operator|*
literal|1024
argument_list|,
literal|'A'
argument_list|,
literal|'Z'
argument_list|)
decl_stmt|;
name|writeDataset
argument_list|(
name|getFileSystem
argument_list|()
argument_list|,
name|path
argument_list|,
name|data2
argument_list|,
name|data2
operator|.
name|length
argument_list|,
literal|1024
argument_list|,
literal|true
argument_list|,
name|useBuilder
argument_list|)
expr_stmt|;
name|ContractTestUtils
operator|.
name|verifyFileContents
argument_list|(
name|getFileSystem
argument_list|()
argument_list|,
name|path
argument_list|,
name|data2
argument_list|)
expr_stmt|;
block|}
comment|/**    * This test catches some eventual consistency problems that blobstores exhibit,    * as we are implicitly verifying that updates are consistent. This    * is why different file lengths and datasets are used    * @throws Throwable    */
annotation|@
name|Test
DECL|method|testOverwriteExistingFile ()
specifier|public
name|void
name|testOverwriteExistingFile
parameter_list|()
throws|throws
name|Throwable
block|{
name|testOverwriteExistingFile
argument_list|(
literal|false
argument_list|)
expr_stmt|;
name|testOverwriteExistingFile
argument_list|(
literal|true
argument_list|)
expr_stmt|;
block|}
DECL|method|testOverwriteEmptyDirectory (boolean useBuilder)
specifier|private
name|void
name|testOverwriteEmptyDirectory
parameter_list|(
name|boolean
name|useBuilder
parameter_list|)
throws|throws
name|Throwable
block|{
name|describe
argument_list|(
literal|"verify trying to create a file over an empty dir fails, "
operator|+
literal|"use builder API="
operator|+
name|useBuilder
argument_list|)
expr_stmt|;
name|Path
name|path
init|=
name|path
argument_list|(
literal|"testOverwriteEmptyDirectory"
argument_list|)
decl_stmt|;
name|mkdirs
argument_list|(
name|path
argument_list|)
expr_stmt|;
name|assertIsDirectory
argument_list|(
name|path
argument_list|)
expr_stmt|;
name|byte
index|[]
name|data
init|=
name|dataset
argument_list|(
literal|256
argument_list|,
literal|'a'
argument_list|,
literal|'z'
argument_list|)
decl_stmt|;
try|try
block|{
name|writeDataset
argument_list|(
name|getFileSystem
argument_list|()
argument_list|,
name|path
argument_list|,
name|data
argument_list|,
name|data
operator|.
name|length
argument_list|,
literal|1024
argument_list|,
literal|true
argument_list|,
name|useBuilder
argument_list|)
expr_stmt|;
name|assertIsDirectory
argument_list|(
name|path
argument_list|)
expr_stmt|;
name|fail
argument_list|(
literal|"write of file over empty dir succeeded"
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|FileAlreadyExistsException
name|expected
parameter_list|)
block|{
comment|//expected
name|handleExpectedException
argument_list|(
name|expected
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|FileNotFoundException
name|e
parameter_list|)
block|{
name|handleRelaxedException
argument_list|(
literal|"overwriting a dir with a file "
argument_list|,
literal|"FileAlreadyExistsException"
argument_list|,
name|e
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|IOException
name|e
parameter_list|)
block|{
name|handleRelaxedException
argument_list|(
literal|"overwriting a dir with a file "
argument_list|,
literal|"FileAlreadyExistsException"
argument_list|,
name|e
argument_list|)
expr_stmt|;
block|}
name|assertIsDirectory
argument_list|(
name|path
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
DECL|method|testOverwriteEmptyDirectory ()
specifier|public
name|void
name|testOverwriteEmptyDirectory
parameter_list|()
throws|throws
name|Throwable
block|{
name|testOverwriteEmptyDirectory
argument_list|(
literal|false
argument_list|)
expr_stmt|;
name|testOverwriteEmptyDirectory
argument_list|(
literal|true
argument_list|)
expr_stmt|;
block|}
DECL|method|testOverwriteNonEmptyDirectory (boolean useBuilder)
specifier|private
name|void
name|testOverwriteNonEmptyDirectory
parameter_list|(
name|boolean
name|useBuilder
parameter_list|)
throws|throws
name|Throwable
block|{
name|describe
argument_list|(
literal|"verify trying to create a file over a non-empty dir fails, "
operator|+
literal|"use builder API="
operator|+
name|useBuilder
argument_list|)
expr_stmt|;
name|Path
name|path
init|=
name|path
argument_list|(
literal|"testOverwriteNonEmptyDirectory"
argument_list|)
decl_stmt|;
name|mkdirs
argument_list|(
name|path
argument_list|)
expr_stmt|;
try|try
block|{
name|assertIsDirectory
argument_list|(
name|path
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|AssertionError
name|failure
parameter_list|)
block|{
if|if
condition|(
name|isSupported
argument_list|(
name|CREATE_OVERWRITES_DIRECTORY
argument_list|)
condition|)
block|{
comment|// file/directory hack surfaces here
throw|throw
operator|new
name|AssumptionViolatedException
argument_list|(
name|failure
operator|.
name|toString
argument_list|()
argument_list|,
name|failure
argument_list|)
throw|;
block|}
comment|// else: rethrow
throw|throw
name|failure
throw|;
block|}
name|Path
name|child
init|=
operator|new
name|Path
argument_list|(
name|path
argument_list|,
literal|"child"
argument_list|)
decl_stmt|;
name|writeTextFile
argument_list|(
name|getFileSystem
argument_list|()
argument_list|,
name|child
argument_list|,
literal|"child file"
argument_list|,
literal|true
argument_list|)
expr_stmt|;
name|byte
index|[]
name|data
init|=
name|dataset
argument_list|(
literal|256
argument_list|,
literal|'a'
argument_list|,
literal|'z'
argument_list|)
decl_stmt|;
try|try
block|{
name|writeDataset
argument_list|(
name|getFileSystem
argument_list|()
argument_list|,
name|path
argument_list|,
name|data
argument_list|,
name|data
operator|.
name|length
argument_list|,
literal|1024
argument_list|,
literal|true
argument_list|,
name|useBuilder
argument_list|)
expr_stmt|;
name|FileStatus
name|status
init|=
name|getFileSystem
argument_list|()
operator|.
name|getFileStatus
argument_list|(
name|path
argument_list|)
decl_stmt|;
name|boolean
name|isDir
init|=
name|status
operator|.
name|isDirectory
argument_list|()
decl_stmt|;
if|if
condition|(
operator|!
name|isDir
operator|&&
name|isSupported
argument_list|(
name|CREATE_OVERWRITES_DIRECTORY
argument_list|)
condition|)
block|{
comment|// For some file systems, downgrade to a skip so that the failure is
comment|// visible in test results.
name|skip
argument_list|(
literal|"This Filesystem allows a file to overwrite a directory"
argument_list|)
expr_stmt|;
block|}
name|fail
argument_list|(
literal|"write of file over dir succeeded"
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|FileAlreadyExistsException
name|expected
parameter_list|)
block|{
comment|//expected
name|handleExpectedException
argument_list|(
name|expected
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|FileNotFoundException
name|e
parameter_list|)
block|{
name|handleRelaxedException
argument_list|(
literal|"overwriting a dir with a file "
argument_list|,
literal|"FileAlreadyExistsException"
argument_list|,
name|e
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|IOException
name|e
parameter_list|)
block|{
name|handleRelaxedException
argument_list|(
literal|"overwriting a dir with a file "
argument_list|,
literal|"FileAlreadyExistsException"
argument_list|,
name|e
argument_list|)
expr_stmt|;
block|}
name|assertIsDirectory
argument_list|(
name|path
argument_list|)
expr_stmt|;
name|assertIsFile
argument_list|(
name|child
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
DECL|method|testOverwriteNonEmptyDirectory ()
specifier|public
name|void
name|testOverwriteNonEmptyDirectory
parameter_list|()
throws|throws
name|Throwable
block|{
name|testOverwriteNonEmptyDirectory
argument_list|(
literal|false
argument_list|)
expr_stmt|;
name|testOverwriteNonEmptyDirectory
argument_list|(
literal|true
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
DECL|method|testCreatedFileIsImmediatelyVisible ()
specifier|public
name|void
name|testCreatedFileIsImmediatelyVisible
parameter_list|()
throws|throws
name|Throwable
block|{
name|describe
argument_list|(
literal|"verify that a newly created file exists as soon as open returns"
argument_list|)
expr_stmt|;
name|Path
name|path
init|=
name|path
argument_list|(
literal|"testCreatedFileIsImmediatelyVisible"
argument_list|)
decl_stmt|;
try|try
init|(
name|FSDataOutputStream
name|out
init|=
name|getFileSystem
argument_list|()
operator|.
name|create
argument_list|(
name|path
argument_list|,
literal|false
argument_list|,
literal|4096
argument_list|,
operator|(
name|short
operator|)
literal|1
argument_list|,
literal|1024
argument_list|)
init|)
block|{
if|if
condition|(
operator|!
name|getFileSystem
argument_list|()
operator|.
name|exists
argument_list|(
name|path
argument_list|)
condition|)
block|{
if|if
condition|(
name|isSupported
argument_list|(
name|CREATE_VISIBILITY_DELAYED
argument_list|)
condition|)
block|{
comment|// For some file systems, downgrade to a skip so that the failure is
comment|// visible in test results.
name|skip
argument_list|(
literal|"This Filesystem delays visibility of newly created files"
argument_list|)
expr_stmt|;
block|}
name|assertPathExists
argument_list|(
literal|"expected path to be visible before anything written"
argument_list|,
name|path
argument_list|)
expr_stmt|;
block|}
block|}
block|}
annotation|@
name|Test
DECL|method|testCreatedFileIsVisibleOnFlush ()
specifier|public
name|void
name|testCreatedFileIsVisibleOnFlush
parameter_list|()
throws|throws
name|Throwable
block|{
name|describe
argument_list|(
literal|"verify that a newly created file exists once a flush has taken "
operator|+
literal|"place"
argument_list|)
expr_stmt|;
name|Path
name|path
init|=
name|path
argument_list|(
literal|"testCreatedFileIsVisibleOnFlush"
argument_list|)
decl_stmt|;
name|FileSystem
name|fs
init|=
name|getFileSystem
argument_list|()
decl_stmt|;
try|try
init|(
name|FSDataOutputStream
name|out
init|=
name|fs
operator|.
name|create
argument_list|(
name|path
argument_list|,
literal|false
argument_list|,
literal|4096
argument_list|,
operator|(
name|short
operator|)
literal|1
argument_list|,
literal|1024
argument_list|)
init|)
block|{
name|out
operator|.
name|write
argument_list|(
literal|'a'
argument_list|)
expr_stmt|;
name|out
operator|.
name|flush
argument_list|()
expr_stmt|;
if|if
condition|(
operator|!
name|fs
operator|.
name|exists
argument_list|(
name|path
argument_list|)
condition|)
block|{
if|if
condition|(
name|isSupported
argument_list|(
name|IS_BLOBSTORE
argument_list|)
operator|||
name|isSupported
argument_list|(
name|CREATE_VISIBILITY_DELAYED
argument_list|)
condition|)
block|{
comment|// object store or some file systems: downgrade to a skip so that the
comment|// failure is visible in test results
name|skip
argument_list|(
literal|"For object store or some file systems, newly created files are"
operator|+
literal|" not immediately visible"
argument_list|)
expr_stmt|;
block|}
name|assertPathExists
argument_list|(
literal|"expected path to be visible before file closed"
argument_list|,
name|path
argument_list|)
expr_stmt|;
block|}
block|}
block|}
annotation|@
name|Test
DECL|method|testCreatedFileIsEventuallyVisible ()
specifier|public
name|void
name|testCreatedFileIsEventuallyVisible
parameter_list|()
throws|throws
name|Throwable
block|{
name|describe
argument_list|(
literal|"verify a written to file is visible after the stream is closed"
argument_list|)
expr_stmt|;
name|Path
name|path
init|=
name|path
argument_list|(
literal|"testCreatedFileIsEventuallyVisible"
argument_list|)
decl_stmt|;
name|FileSystem
name|fs
init|=
name|getFileSystem
argument_list|()
decl_stmt|;
try|try
init|(
name|FSDataOutputStream
name|out
init|=
name|fs
operator|.
name|create
argument_list|(
name|path
argument_list|,
literal|false
argument_list|,
literal|4096
argument_list|,
operator|(
name|short
operator|)
literal|1
argument_list|,
literal|1024
argument_list|)
init|)
block|{
name|out
operator|.
name|write
argument_list|(
literal|0x01
argument_list|)
expr_stmt|;
name|out
operator|.
name|close
argument_list|()
expr_stmt|;
name|getFileStatusEventually
argument_list|(
name|fs
argument_list|,
name|path
argument_list|,
name|CREATE_TIMEOUT
argument_list|)
expr_stmt|;
block|}
block|}
annotation|@
name|Test
DECL|method|testFileStatusBlocksizeNonEmptyFile ()
specifier|public
name|void
name|testFileStatusBlocksizeNonEmptyFile
parameter_list|()
throws|throws
name|Throwable
block|{
name|describe
argument_list|(
literal|"validate the block size of a filesystem and files within it"
argument_list|)
expr_stmt|;
name|FileSystem
name|fs
init|=
name|getFileSystem
argument_list|()
decl_stmt|;
name|long
name|rootPath
init|=
name|fs
operator|.
name|getDefaultBlockSize
argument_list|(
name|path
argument_list|(
literal|"/"
argument_list|)
argument_list|)
decl_stmt|;
name|assertTrue
argument_list|(
literal|"Root block size is invalid "
operator|+
name|rootPath
argument_list|,
name|rootPath
operator|>
literal|0
argument_list|)
expr_stmt|;
name|Path
name|path
init|=
name|path
argument_list|(
literal|"testFileStatusBlocksizeNonEmptyFile"
argument_list|)
decl_stmt|;
name|byte
index|[]
name|data
init|=
name|dataset
argument_list|(
literal|256
argument_list|,
literal|'a'
argument_list|,
literal|'z'
argument_list|)
decl_stmt|;
name|writeDataset
argument_list|(
name|fs
argument_list|,
name|path
argument_list|,
name|data
argument_list|,
name|data
operator|.
name|length
argument_list|,
literal|1024
operator|*
literal|1024
argument_list|,
literal|false
argument_list|)
expr_stmt|;
name|validateBlockSize
argument_list|(
name|fs
argument_list|,
name|path
argument_list|,
literal|1
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
DECL|method|testFileStatusBlocksizeEmptyFile ()
specifier|public
name|void
name|testFileStatusBlocksizeEmptyFile
parameter_list|()
throws|throws
name|Throwable
block|{
name|describe
argument_list|(
literal|"check that an empty file may return a 0-byte blocksize"
argument_list|)
expr_stmt|;
name|FileSystem
name|fs
init|=
name|getFileSystem
argument_list|()
decl_stmt|;
name|Path
name|path
init|=
name|path
argument_list|(
literal|"testFileStatusBlocksizeEmptyFile"
argument_list|)
decl_stmt|;
name|ContractTestUtils
operator|.
name|touch
argument_list|(
name|fs
argument_list|,
name|path
argument_list|)
expr_stmt|;
name|validateBlockSize
argument_list|(
name|fs
argument_list|,
name|path
argument_list|,
literal|0
argument_list|)
expr_stmt|;
block|}
DECL|method|validateBlockSize (FileSystem fs, Path path, int minValue)
specifier|private
name|void
name|validateBlockSize
parameter_list|(
name|FileSystem
name|fs
parameter_list|,
name|Path
name|path
parameter_list|,
name|int
name|minValue
parameter_list|)
throws|throws
name|IOException
throws|,
name|InterruptedException
block|{
name|FileStatus
name|status
init|=
name|getFileStatusEventually
argument_list|(
name|fs
argument_list|,
name|path
argument_list|,
name|CREATE_TIMEOUT
argument_list|)
decl_stmt|;
name|String
name|statusDetails
init|=
name|status
operator|.
name|toString
argument_list|()
decl_stmt|;
name|assertTrue
argument_list|(
literal|"File status block size too low:  "
operator|+
name|statusDetails
operator|+
literal|" min value: "
operator|+
name|minValue
argument_list|,
name|status
operator|.
name|getBlockSize
argument_list|()
operator|>=
name|minValue
argument_list|)
expr_stmt|;
name|long
name|defaultBlockSize
init|=
name|fs
operator|.
name|getDefaultBlockSize
argument_list|(
name|path
argument_list|)
decl_stmt|;
name|assertTrue
argument_list|(
literal|"fs.getDefaultBlockSize("
operator|+
name|path
operator|+
literal|") size "
operator|+
name|defaultBlockSize
operator|+
literal|" is below the minimum of "
operator|+
name|minValue
argument_list|,
name|defaultBlockSize
operator|>=
name|minValue
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
DECL|method|testCreateMakesParentDirs ()
specifier|public
name|void
name|testCreateMakesParentDirs
parameter_list|()
throws|throws
name|Throwable
block|{
name|describe
argument_list|(
literal|"check that after creating a file its parent directories exist"
argument_list|)
expr_stmt|;
name|FileSystem
name|fs
init|=
name|getFileSystem
argument_list|()
decl_stmt|;
name|Path
name|grandparent
init|=
name|path
argument_list|(
literal|"testCreateCreatesAndPopulatesParents"
argument_list|)
decl_stmt|;
name|Path
name|parent
init|=
operator|new
name|Path
argument_list|(
name|grandparent
argument_list|,
literal|"parent"
argument_list|)
decl_stmt|;
name|Path
name|child
init|=
operator|new
name|Path
argument_list|(
name|parent
argument_list|,
literal|"child"
argument_list|)
decl_stmt|;
name|touch
argument_list|(
name|fs
argument_list|,
name|child
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"List status of parent should include the 1 child file"
argument_list|,
literal|1
argument_list|,
name|fs
operator|.
name|listStatus
argument_list|(
name|parent
argument_list|)
operator|.
name|length
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
literal|"Parent directory does not appear to be a directory"
argument_list|,
name|fs
operator|.
name|getFileStatus
argument_list|(
name|parent
argument_list|)
operator|.
name|isDirectory
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"List status of grandparent should include the 1 parent dir"
argument_list|,
literal|1
argument_list|,
name|fs
operator|.
name|listStatus
argument_list|(
name|grandparent
argument_list|)
operator|.
name|length
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
literal|"Grandparent directory does not appear to be a directory"
argument_list|,
name|fs
operator|.
name|getFileStatus
argument_list|(
name|grandparent
argument_list|)
operator|.
name|isDirectory
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

