begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements.  See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership.  The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|org.apache.hadoop.mapreduce.v2.hs
package|package
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|mapreduce
operator|.
name|v2
operator|.
name|hs
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Collection
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Map
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|SortedMap
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|TreeMap
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|cache
operator|.
name|Cache
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|cache
operator|.
name|CacheBuilder
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|cache
operator|.
name|CacheLoader
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|cache
operator|.
name|LoadingCache
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|cache
operator|.
name|Weigher
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|util
operator|.
name|concurrent
operator|.
name|UncheckedExecutionException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|conf
operator|.
name|Configuration
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|mapreduce
operator|.
name|v2
operator|.
name|api
operator|.
name|records
operator|.
name|JobId
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|mapreduce
operator|.
name|v2
operator|.
name|api
operator|.
name|records
operator|.
name|JobReport
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|mapreduce
operator|.
name|v2
operator|.
name|api
operator|.
name|records
operator|.
name|JobState
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|mapreduce
operator|.
name|v2
operator|.
name|app
operator|.
name|job
operator|.
name|Job
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|mapreduce
operator|.
name|v2
operator|.
name|hs
operator|.
name|webapp
operator|.
name|dao
operator|.
name|JobsInfo
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|mapreduce
operator|.
name|v2
operator|.
name|hs
operator|.
name|HistoryFileManager
operator|.
name|HistoryFileInfo
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|mapreduce
operator|.
name|v2
operator|.
name|hs
operator|.
name|webapp
operator|.
name|dao
operator|.
name|JobInfo
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|mapreduce
operator|.
name|v2
operator|.
name|jobhistory
operator|.
name|JHAdminConfig
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|service
operator|.
name|AbstractService
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|yarn
operator|.
name|exceptions
operator|.
name|YarnRuntimeException
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|annotations
operator|.
name|VisibleForTesting
import|;
end_import

begin_import
import|import
name|org
operator|.
name|slf4j
operator|.
name|Logger
import|;
end_import

begin_import
import|import
name|org
operator|.
name|slf4j
operator|.
name|LoggerFactory
import|;
end_import

begin_comment
comment|/**  * Manages an in memory cache of parsed Job History files.  */
end_comment

begin_class
DECL|class|CachedHistoryStorage
specifier|public
class|class
name|CachedHistoryStorage
extends|extends
name|AbstractService
implements|implements
name|HistoryStorage
block|{
DECL|field|LOG
specifier|private
specifier|static
specifier|final
name|Logger
name|LOG
init|=
name|LoggerFactory
operator|.
name|getLogger
argument_list|(
name|CachedHistoryStorage
operator|.
name|class
argument_list|)
decl_stmt|;
DECL|field|loadedJobCache
specifier|private
name|LoadingCache
argument_list|<
name|JobId
argument_list|,
name|Job
argument_list|>
name|loadedJobCache
init|=
literal|null
decl_stmt|;
DECL|field|loadedJobCacheSize
specifier|private
name|int
name|loadedJobCacheSize
decl_stmt|;
DECL|field|loadedTasksCacheSize
specifier|private
name|int
name|loadedTasksCacheSize
decl_stmt|;
DECL|field|useLoadedTasksCache
specifier|private
name|boolean
name|useLoadedTasksCache
decl_stmt|;
DECL|field|hsManager
specifier|private
name|HistoryFileManager
name|hsManager
decl_stmt|;
annotation|@
name|Override
DECL|method|setHistoryFileManager (HistoryFileManager hsManager)
specifier|public
name|void
name|setHistoryFileManager
parameter_list|(
name|HistoryFileManager
name|hsManager
parameter_list|)
block|{
name|this
operator|.
name|hsManager
operator|=
name|hsManager
expr_stmt|;
block|}
annotation|@
name|Override
DECL|method|serviceInit (Configuration conf)
specifier|public
name|void
name|serviceInit
parameter_list|(
name|Configuration
name|conf
parameter_list|)
throws|throws
name|Exception
block|{
name|super
operator|.
name|serviceInit
argument_list|(
name|conf
argument_list|)
expr_stmt|;
name|LOG
operator|.
name|info
argument_list|(
literal|"CachedHistoryStorage Init"
argument_list|)
expr_stmt|;
name|createLoadedJobCache
argument_list|(
name|conf
argument_list|)
expr_stmt|;
block|}
annotation|@
name|SuppressWarnings
argument_list|(
literal|"serial"
argument_list|)
DECL|method|createLoadedJobCache (Configuration conf)
specifier|private
name|void
name|createLoadedJobCache
parameter_list|(
name|Configuration
name|conf
parameter_list|)
block|{
comment|// Set property for old "loaded jobs" cache
name|loadedJobCacheSize
operator|=
name|conf
operator|.
name|getInt
argument_list|(
name|JHAdminConfig
operator|.
name|MR_HISTORY_LOADED_JOB_CACHE_SIZE
argument_list|,
name|JHAdminConfig
operator|.
name|DEFAULT_MR_HISTORY_LOADED_JOB_CACHE_SIZE
argument_list|)
expr_stmt|;
comment|// Check property for new "loaded tasks" cache perform sanity checking
name|useLoadedTasksCache
operator|=
literal|false
expr_stmt|;
try|try
block|{
name|String
name|taskSizeString
init|=
name|conf
operator|.
name|get
argument_list|(
name|JHAdminConfig
operator|.
name|MR_HISTORY_LOADED_TASKS_CACHE_SIZE
argument_list|)
decl_stmt|;
if|if
condition|(
name|taskSizeString
operator|!=
literal|null
condition|)
block|{
name|loadedTasksCacheSize
operator|=
name|Math
operator|.
name|max
argument_list|(
name|Integer
operator|.
name|parseInt
argument_list|(
name|taskSizeString
argument_list|)
argument_list|,
literal|1
argument_list|)
expr_stmt|;
name|useLoadedTasksCache
operator|=
literal|true
expr_stmt|;
block|}
block|}
catch|catch
parameter_list|(
name|NumberFormatException
name|nfe
parameter_list|)
block|{
name|LOG
operator|.
name|error
argument_list|(
literal|"The property "
operator|+
name|JHAdminConfig
operator|.
name|MR_HISTORY_LOADED_TASKS_CACHE_SIZE
operator|+
literal|" is not an integer value.  Please set it to a positive"
operator|+
literal|" integer value."
argument_list|)
expr_stmt|;
block|}
name|CacheLoader
argument_list|<
name|JobId
argument_list|,
name|Job
argument_list|>
name|loader
decl_stmt|;
name|loader
operator|=
operator|new
name|CacheLoader
argument_list|<
name|JobId
argument_list|,
name|Job
argument_list|>
argument_list|()
block|{
annotation|@
name|Override
specifier|public
name|Job
name|load
parameter_list|(
name|JobId
name|key
parameter_list|)
throws|throws
name|Exception
block|{
return|return
name|loadJob
argument_list|(
name|key
argument_list|)
return|;
block|}
block|}
expr_stmt|;
if|if
condition|(
operator|!
name|useLoadedTasksCache
condition|)
block|{
name|loadedJobCache
operator|=
name|CacheBuilder
operator|.
name|newBuilder
argument_list|()
operator|.
name|maximumSize
argument_list|(
name|loadedJobCacheSize
argument_list|)
operator|.
name|initialCapacity
argument_list|(
name|loadedJobCacheSize
argument_list|)
operator|.
name|concurrencyLevel
argument_list|(
literal|1
argument_list|)
operator|.
name|build
argument_list|(
name|loader
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|Weigher
argument_list|<
name|JobId
argument_list|,
name|Job
argument_list|>
name|weightByTasks
decl_stmt|;
name|weightByTasks
operator|=
operator|new
name|Weigher
argument_list|<
name|JobId
argument_list|,
name|Job
argument_list|>
argument_list|()
block|{
comment|/**          * Method for calculating Job weight by total task count.  If          * the total task count is greater than the size of the tasks          * cache, then cap it at the cache size.  This allows the cache          * to always hold one large job.          * @param key JobId object          * @param value Job object          * @return Weight of the job as calculated by total task count          */
annotation|@
name|Override
specifier|public
name|int
name|weigh
parameter_list|(
name|JobId
name|key
parameter_list|,
name|Job
name|value
parameter_list|)
block|{
name|int
name|taskCount
init|=
name|Math
operator|.
name|min
argument_list|(
name|loadedTasksCacheSize
argument_list|,
name|value
operator|.
name|getTotalMaps
argument_list|()
operator|+
name|value
operator|.
name|getTotalReduces
argument_list|()
argument_list|)
decl_stmt|;
return|return
name|taskCount
return|;
block|}
block|}
expr_stmt|;
comment|// Keep concurrencyLevel at 1.  Otherwise, two problems:
comment|// 1) The largest job that can be initially loaded is
comment|//    cache size / 4.
comment|// 2) Unit tests are not deterministic.
name|loadedJobCache
operator|=
name|CacheBuilder
operator|.
name|newBuilder
argument_list|()
operator|.
name|maximumWeight
argument_list|(
name|loadedTasksCacheSize
argument_list|)
operator|.
name|weigher
argument_list|(
name|weightByTasks
argument_list|)
operator|.
name|concurrencyLevel
argument_list|(
literal|1
argument_list|)
operator|.
name|build
argument_list|(
name|loader
argument_list|)
expr_stmt|;
block|}
block|}
DECL|method|refreshLoadedJobCache ()
specifier|public
name|void
name|refreshLoadedJobCache
parameter_list|()
block|{
if|if
condition|(
name|getServiceState
argument_list|()
operator|==
name|STATE
operator|.
name|STARTED
condition|)
block|{
name|setConfig
argument_list|(
name|createConf
argument_list|()
argument_list|)
expr_stmt|;
name|createLoadedJobCache
argument_list|(
name|getConfig
argument_list|()
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|LOG
operator|.
name|warn
argument_list|(
literal|"Failed to execute refreshLoadedJobCache: CachedHistoryStorage is not started"
argument_list|)
expr_stmt|;
block|}
block|}
annotation|@
name|VisibleForTesting
DECL|method|createConf ()
name|Configuration
name|createConf
parameter_list|()
block|{
return|return
operator|new
name|Configuration
argument_list|()
return|;
block|}
DECL|method|CachedHistoryStorage ()
specifier|public
name|CachedHistoryStorage
parameter_list|()
block|{
name|super
argument_list|(
name|CachedHistoryStorage
operator|.
name|class
operator|.
name|getName
argument_list|()
argument_list|)
expr_stmt|;
block|}
DECL|class|HSFileRuntimeException
specifier|private
specifier|static
class|class
name|HSFileRuntimeException
extends|extends
name|RuntimeException
block|{
DECL|method|HSFileRuntimeException (String message)
specifier|public
name|HSFileRuntimeException
parameter_list|(
name|String
name|message
parameter_list|)
block|{
name|super
argument_list|(
name|message
argument_list|)
expr_stmt|;
block|}
block|}
DECL|method|loadJob (JobId jobId)
specifier|private
name|Job
name|loadJob
parameter_list|(
name|JobId
name|jobId
parameter_list|)
throws|throws
name|RuntimeException
throws|,
name|IOException
block|{
if|if
condition|(
name|LOG
operator|.
name|isDebugEnabled
argument_list|()
condition|)
block|{
name|LOG
operator|.
name|debug
argument_list|(
literal|"Looking for Job "
operator|+
name|jobId
argument_list|)
expr_stmt|;
block|}
name|HistoryFileInfo
name|fileInfo
decl_stmt|;
name|fileInfo
operator|=
name|hsManager
operator|.
name|getFileInfo
argument_list|(
name|jobId
argument_list|)
expr_stmt|;
if|if
condition|(
name|fileInfo
operator|==
literal|null
condition|)
block|{
throw|throw
operator|new
name|HSFileRuntimeException
argument_list|(
literal|"Unable to find job "
operator|+
name|jobId
argument_list|)
throw|;
block|}
name|fileInfo
operator|.
name|waitUntilMoved
argument_list|()
expr_stmt|;
if|if
condition|(
name|fileInfo
operator|.
name|isDeleted
argument_list|()
condition|)
block|{
throw|throw
operator|new
name|HSFileRuntimeException
argument_list|(
literal|"Cannot load deleted job "
operator|+
name|jobId
argument_list|)
throw|;
block|}
else|else
block|{
return|return
name|fileInfo
operator|.
name|loadJob
argument_list|()
return|;
block|}
block|}
annotation|@
name|VisibleForTesting
DECL|method|getLoadedJobCache ()
name|Cache
argument_list|<
name|JobId
argument_list|,
name|Job
argument_list|>
name|getLoadedJobCache
parameter_list|()
block|{
return|return
name|loadedJobCache
return|;
block|}
annotation|@
name|Override
DECL|method|getFullJob (JobId jobId)
specifier|public
name|Job
name|getFullJob
parameter_list|(
name|JobId
name|jobId
parameter_list|)
block|{
name|Job
name|retVal
init|=
literal|null
decl_stmt|;
try|try
block|{
name|retVal
operator|=
name|loadedJobCache
operator|.
name|getUnchecked
argument_list|(
name|jobId
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|UncheckedExecutionException
name|e
parameter_list|)
block|{
if|if
condition|(
name|e
operator|.
name|getCause
argument_list|()
operator|instanceof
name|HSFileRuntimeException
condition|)
block|{
name|LOG
operator|.
name|error
argument_list|(
name|e
operator|.
name|getCause
argument_list|()
operator|.
name|getMessage
argument_list|()
argument_list|)
expr_stmt|;
return|return
literal|null
return|;
block|}
else|else
block|{
throw|throw
operator|new
name|YarnRuntimeException
argument_list|(
name|e
operator|.
name|getCause
argument_list|()
argument_list|)
throw|;
block|}
block|}
return|return
name|retVal
return|;
block|}
annotation|@
name|Override
DECL|method|getAllPartialJobs ()
specifier|public
name|Map
argument_list|<
name|JobId
argument_list|,
name|Job
argument_list|>
name|getAllPartialJobs
parameter_list|()
block|{
name|LOG
operator|.
name|debug
argument_list|(
literal|"Called getAllPartialJobs()"
argument_list|)
expr_stmt|;
name|SortedMap
argument_list|<
name|JobId
argument_list|,
name|Job
argument_list|>
name|result
init|=
operator|new
name|TreeMap
argument_list|<
name|JobId
argument_list|,
name|Job
argument_list|>
argument_list|()
decl_stmt|;
try|try
block|{
for|for
control|(
name|HistoryFileInfo
name|mi
range|:
name|hsManager
operator|.
name|getAllFileInfo
argument_list|()
control|)
block|{
if|if
condition|(
name|mi
operator|!=
literal|null
condition|)
block|{
name|JobId
name|id
init|=
name|mi
operator|.
name|getJobId
argument_list|()
decl_stmt|;
name|mi
operator|.
name|waitUntilMoved
argument_list|()
expr_stmt|;
name|result
operator|.
name|put
argument_list|(
name|id
argument_list|,
operator|new
name|PartialJob
argument_list|(
name|mi
operator|.
name|getJobIndexInfo
argument_list|()
argument_list|,
name|id
argument_list|)
argument_list|)
expr_stmt|;
block|}
block|}
block|}
catch|catch
parameter_list|(
name|IOException
name|e
parameter_list|)
block|{
name|LOG
operator|.
name|warn
argument_list|(
literal|"Error trying to scan for all FileInfos"
argument_list|,
name|e
argument_list|)
expr_stmt|;
throw|throw
operator|new
name|YarnRuntimeException
argument_list|(
name|e
argument_list|)
throw|;
block|}
return|return
name|result
return|;
block|}
annotation|@
name|Override
DECL|method|getPartialJobs (Long offset, Long count, String user, String queue, Long sBegin, Long sEnd, Long fBegin, Long fEnd, JobState jobState)
specifier|public
name|JobsInfo
name|getPartialJobs
parameter_list|(
name|Long
name|offset
parameter_list|,
name|Long
name|count
parameter_list|,
name|String
name|user
parameter_list|,
name|String
name|queue
parameter_list|,
name|Long
name|sBegin
parameter_list|,
name|Long
name|sEnd
parameter_list|,
name|Long
name|fBegin
parameter_list|,
name|Long
name|fEnd
parameter_list|,
name|JobState
name|jobState
parameter_list|)
block|{
return|return
name|getPartialJobs
argument_list|(
name|getAllPartialJobs
argument_list|()
operator|.
name|values
argument_list|()
argument_list|,
name|offset
argument_list|,
name|count
argument_list|,
name|user
argument_list|,
name|queue
argument_list|,
name|sBegin
argument_list|,
name|sEnd
argument_list|,
name|fBegin
argument_list|,
name|fEnd
argument_list|,
name|jobState
argument_list|)
return|;
block|}
DECL|method|getPartialJobs (Collection<Job> jobs, Long offset, Long count, String user, String queue, Long sBegin, Long sEnd, Long fBegin, Long fEnd, JobState jobState)
specifier|public
specifier|static
name|JobsInfo
name|getPartialJobs
parameter_list|(
name|Collection
argument_list|<
name|Job
argument_list|>
name|jobs
parameter_list|,
name|Long
name|offset
parameter_list|,
name|Long
name|count
parameter_list|,
name|String
name|user
parameter_list|,
name|String
name|queue
parameter_list|,
name|Long
name|sBegin
parameter_list|,
name|Long
name|sEnd
parameter_list|,
name|Long
name|fBegin
parameter_list|,
name|Long
name|fEnd
parameter_list|,
name|JobState
name|jobState
parameter_list|)
block|{
name|JobsInfo
name|allJobs
init|=
operator|new
name|JobsInfo
argument_list|()
decl_stmt|;
if|if
condition|(
name|sBegin
operator|==
literal|null
operator|||
name|sBegin
operator|<
literal|0
condition|)
name|sBegin
operator|=
literal|0l
expr_stmt|;
if|if
condition|(
name|sEnd
operator|==
literal|null
condition|)
name|sEnd
operator|=
name|Long
operator|.
name|MAX_VALUE
expr_stmt|;
if|if
condition|(
name|fBegin
operator|==
literal|null
operator|||
name|fBegin
operator|<
literal|0
condition|)
name|fBegin
operator|=
literal|0l
expr_stmt|;
if|if
condition|(
name|fEnd
operator|==
literal|null
condition|)
name|fEnd
operator|=
name|Long
operator|.
name|MAX_VALUE
expr_stmt|;
if|if
condition|(
name|offset
operator|==
literal|null
operator|||
name|offset
operator|<
literal|0
condition|)
name|offset
operator|=
literal|0l
expr_stmt|;
if|if
condition|(
name|count
operator|==
literal|null
condition|)
name|count
operator|=
name|Long
operator|.
name|MAX_VALUE
expr_stmt|;
if|if
condition|(
name|offset
operator|>
name|jobs
operator|.
name|size
argument_list|()
condition|)
block|{
return|return
name|allJobs
return|;
block|}
name|long
name|at
init|=
literal|0
decl_stmt|;
name|long
name|end
init|=
name|offset
operator|+
name|count
operator|-
literal|1
decl_stmt|;
if|if
condition|(
name|end
operator|<
literal|0
condition|)
block|{
comment|// due to overflow
name|end
operator|=
name|Long
operator|.
name|MAX_VALUE
expr_stmt|;
block|}
for|for
control|(
name|Job
name|job
range|:
name|jobs
control|)
block|{
if|if
condition|(
name|at
operator|>
name|end
condition|)
block|{
break|break;
block|}
comment|// can't really validate queue is a valid one since queues could change
if|if
condition|(
name|queue
operator|!=
literal|null
operator|&&
operator|!
name|queue
operator|.
name|isEmpty
argument_list|()
condition|)
block|{
if|if
condition|(
operator|!
name|job
operator|.
name|getQueueName
argument_list|()
operator|.
name|equals
argument_list|(
name|queue
argument_list|)
condition|)
block|{
continue|continue;
block|}
block|}
if|if
condition|(
name|user
operator|!=
literal|null
operator|&&
operator|!
name|user
operator|.
name|isEmpty
argument_list|()
condition|)
block|{
if|if
condition|(
operator|!
name|job
operator|.
name|getUserName
argument_list|()
operator|.
name|equals
argument_list|(
name|user
argument_list|)
condition|)
block|{
continue|continue;
block|}
block|}
name|JobReport
name|report
init|=
name|job
operator|.
name|getReport
argument_list|()
decl_stmt|;
if|if
condition|(
name|report
operator|.
name|getStartTime
argument_list|()
operator|<
name|sBegin
operator|||
name|report
operator|.
name|getStartTime
argument_list|()
operator|>
name|sEnd
condition|)
block|{
continue|continue;
block|}
if|if
condition|(
name|report
operator|.
name|getFinishTime
argument_list|()
operator|<
name|fBegin
operator|||
name|report
operator|.
name|getFinishTime
argument_list|()
operator|>
name|fEnd
condition|)
block|{
continue|continue;
block|}
if|if
condition|(
name|jobState
operator|!=
literal|null
operator|&&
name|jobState
operator|!=
name|report
operator|.
name|getJobState
argument_list|()
condition|)
block|{
continue|continue;
block|}
name|at
operator|++
expr_stmt|;
if|if
condition|(
operator|(
name|at
operator|-
literal|1
operator|)
operator|<
name|offset
condition|)
block|{
continue|continue;
block|}
name|JobInfo
name|jobInfo
init|=
operator|new
name|JobInfo
argument_list|(
name|job
argument_list|)
decl_stmt|;
name|allJobs
operator|.
name|add
argument_list|(
name|jobInfo
argument_list|)
expr_stmt|;
block|}
return|return
name|allJobs
return|;
block|}
annotation|@
name|VisibleForTesting
DECL|method|getUseLoadedTasksCache ()
specifier|public
name|boolean
name|getUseLoadedTasksCache
parameter_list|()
block|{
return|return
name|useLoadedTasksCache
return|;
block|}
annotation|@
name|VisibleForTesting
DECL|method|getLoadedTasksCacheSize ()
specifier|public
name|int
name|getLoadedTasksCacheSize
parameter_list|()
block|{
return|return
name|loadedTasksCacheSize
return|;
block|}
block|}
end_class

end_unit

