begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements.  See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership.  The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|org.apache.hadoop.yarn.api.records.impl.pb
package|package
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|yarn
operator|.
name|api
operator|.
name|records
operator|.
name|impl
operator|.
name|pb
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|yarn
operator|.
name|api
operator|.
name|records
operator|.
name|UpdateContainerError
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|yarn
operator|.
name|api
operator|.
name|records
operator|.
name|UpdateContainerRequest
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|yarn
operator|.
name|proto
operator|.
name|YarnServiceProtos
import|;
end_import

begin_comment
comment|/**  * Implementation of<code>UpdateContainerError</code>.  */
end_comment

begin_class
DECL|class|UpdateContainerErrorPBImpl
specifier|public
class|class
name|UpdateContainerErrorPBImpl
extends|extends
name|UpdateContainerError
block|{
DECL|field|proto
specifier|private
name|YarnServiceProtos
operator|.
name|UpdateContainerErrorProto
name|proto
init|=
name|YarnServiceProtos
operator|.
name|UpdateContainerErrorProto
operator|.
name|getDefaultInstance
argument_list|()
decl_stmt|;
DECL|field|builder
specifier|private
name|YarnServiceProtos
operator|.
name|UpdateContainerErrorProto
operator|.
name|Builder
name|builder
init|=
literal|null
decl_stmt|;
DECL|field|viaProto
specifier|private
name|boolean
name|viaProto
init|=
literal|false
decl_stmt|;
DECL|field|reason
specifier|private
name|String
name|reason
init|=
literal|null
decl_stmt|;
DECL|field|updateRequest
specifier|private
name|UpdateContainerRequest
name|updateRequest
init|=
literal|null
decl_stmt|;
DECL|method|UpdateContainerErrorPBImpl ()
specifier|public
name|UpdateContainerErrorPBImpl
parameter_list|()
block|{
name|builder
operator|=
name|YarnServiceProtos
operator|.
name|UpdateContainerErrorProto
operator|.
name|newBuilder
argument_list|()
expr_stmt|;
block|}
DECL|method|UpdateContainerErrorPBImpl (YarnServiceProtos .UpdateContainerErrorProto proto)
specifier|public
name|UpdateContainerErrorPBImpl
parameter_list|(
name|YarnServiceProtos
operator|.
name|UpdateContainerErrorProto
name|proto
parameter_list|)
block|{
name|this
operator|.
name|proto
operator|=
name|proto
expr_stmt|;
name|viaProto
operator|=
literal|true
expr_stmt|;
block|}
DECL|method|getProto ()
specifier|public
name|YarnServiceProtos
operator|.
name|UpdateContainerErrorProto
name|getProto
parameter_list|()
block|{
name|mergeLocalToProto
argument_list|()
expr_stmt|;
name|proto
operator|=
name|viaProto
condition|?
name|proto
else|:
name|builder
operator|.
name|build
argument_list|()
expr_stmt|;
name|viaProto
operator|=
literal|true
expr_stmt|;
return|return
name|proto
return|;
block|}
annotation|@
name|Override
DECL|method|getReason ()
specifier|public
name|String
name|getReason
parameter_list|()
block|{
name|YarnServiceProtos
operator|.
name|UpdateContainerErrorProtoOrBuilder
name|p
init|=
name|viaProto
condition|?
name|proto
else|:
name|builder
decl_stmt|;
if|if
condition|(
name|this
operator|.
name|reason
operator|!=
literal|null
condition|)
block|{
return|return
name|this
operator|.
name|reason
return|;
block|}
if|if
condition|(
name|p
operator|.
name|hasReason
argument_list|()
condition|)
block|{
name|this
operator|.
name|reason
operator|=
name|p
operator|.
name|getReason
argument_list|()
expr_stmt|;
block|}
return|return
name|this
operator|.
name|reason
return|;
block|}
annotation|@
name|Override
DECL|method|setReason (String reason)
specifier|public
name|void
name|setReason
parameter_list|(
name|String
name|reason
parameter_list|)
block|{
name|maybeInitBuilder
argument_list|()
expr_stmt|;
if|if
condition|(
name|reason
operator|==
literal|null
condition|)
block|{
name|builder
operator|.
name|clearReason
argument_list|()
expr_stmt|;
block|}
name|this
operator|.
name|reason
operator|=
name|reason
expr_stmt|;
block|}
annotation|@
name|Override
DECL|method|getCurrentContainerVersion ()
specifier|public
name|int
name|getCurrentContainerVersion
parameter_list|()
block|{
name|YarnServiceProtos
operator|.
name|UpdateContainerErrorProtoOrBuilder
name|p
init|=
name|viaProto
condition|?
name|proto
else|:
name|builder
decl_stmt|;
if|if
condition|(
operator|!
name|p
operator|.
name|hasCurrentContainerVersion
argument_list|()
condition|)
block|{
return|return
literal|0
return|;
block|}
return|return
name|p
operator|.
name|getCurrentContainerVersion
argument_list|()
return|;
block|}
annotation|@
name|Override
DECL|method|setCurrentContainerVersion (int containerVersion)
specifier|public
name|void
name|setCurrentContainerVersion
parameter_list|(
name|int
name|containerVersion
parameter_list|)
block|{
name|maybeInitBuilder
argument_list|()
expr_stmt|;
name|builder
operator|.
name|setCurrentContainerVersion
argument_list|(
name|containerVersion
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
DECL|method|getUpdateContainerRequest ()
specifier|public
name|UpdateContainerRequest
name|getUpdateContainerRequest
parameter_list|()
block|{
name|YarnServiceProtos
operator|.
name|UpdateContainerErrorProtoOrBuilder
name|p
init|=
name|viaProto
condition|?
name|proto
else|:
name|builder
decl_stmt|;
if|if
condition|(
name|this
operator|.
name|updateRequest
operator|!=
literal|null
condition|)
block|{
return|return
name|this
operator|.
name|updateRequest
return|;
block|}
if|if
condition|(
name|p
operator|.
name|hasUpdateRequest
argument_list|()
condition|)
block|{
name|this
operator|.
name|updateRequest
operator|=
name|ProtoUtils
operator|.
name|convertFromProtoFormat
argument_list|(
name|p
operator|.
name|getUpdateRequest
argument_list|()
argument_list|)
expr_stmt|;
block|}
return|return
name|this
operator|.
name|updateRequest
return|;
block|}
annotation|@
name|Override
DECL|method|setUpdateContainerRequest ( UpdateContainerRequest updateContainerRequest)
specifier|public
name|void
name|setUpdateContainerRequest
parameter_list|(
name|UpdateContainerRequest
name|updateContainerRequest
parameter_list|)
block|{
name|maybeInitBuilder
argument_list|()
expr_stmt|;
if|if
condition|(
name|updateContainerRequest
operator|==
literal|null
condition|)
block|{
name|builder
operator|.
name|clearUpdateRequest
argument_list|()
expr_stmt|;
block|}
name|this
operator|.
name|updateRequest
operator|=
name|updateContainerRequest
expr_stmt|;
block|}
DECL|method|mergeLocalToProto ()
specifier|private
name|void
name|mergeLocalToProto
parameter_list|()
block|{
if|if
condition|(
name|viaProto
condition|)
block|{
name|maybeInitBuilder
argument_list|()
expr_stmt|;
block|}
name|mergeLocalToBuilder
argument_list|()
expr_stmt|;
name|proto
operator|=
name|builder
operator|.
name|build
argument_list|()
expr_stmt|;
name|viaProto
operator|=
literal|true
expr_stmt|;
block|}
DECL|method|maybeInitBuilder ()
specifier|private
name|void
name|maybeInitBuilder
parameter_list|()
block|{
if|if
condition|(
name|viaProto
operator|||
name|builder
operator|==
literal|null
condition|)
block|{
name|builder
operator|=
name|YarnServiceProtos
operator|.
name|UpdateContainerErrorProto
operator|.
name|newBuilder
argument_list|(
name|proto
argument_list|)
expr_stmt|;
block|}
name|viaProto
operator|=
literal|false
expr_stmt|;
block|}
DECL|method|mergeLocalToBuilder ()
specifier|private
name|void
name|mergeLocalToBuilder
parameter_list|()
block|{
if|if
condition|(
name|this
operator|.
name|reason
operator|!=
literal|null
condition|)
block|{
name|builder
operator|.
name|setReason
argument_list|(
name|this
operator|.
name|reason
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|this
operator|.
name|updateRequest
operator|!=
literal|null
condition|)
block|{
name|builder
operator|.
name|setUpdateRequest
argument_list|(
name|ProtoUtils
operator|.
name|convertToProtoFormat
argument_list|(
name|this
operator|.
name|updateRequest
argument_list|)
argument_list|)
expr_stmt|;
block|}
block|}
block|}
end_class

end_unit

