begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements.ââSee the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership.ââThe ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  *  with the License.ââYou may obtain a copy of the License at  *  * ââââ http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|org.apache.hadoop.ozone.om.helpers
package|package
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|ozone
operator|.
name|om
operator|.
name|helpers
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|crypto
operator|.
name|CipherSuite
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|crypto
operator|.
name|CryptoProtocolVersion
import|;
end_import

begin_comment
comment|/**  * Encryption key info for bucket encryption key.  */
end_comment

begin_class
DECL|class|BucketEncryptionKeyInfo
specifier|public
class|class
name|BucketEncryptionKeyInfo
block|{
DECL|field|version
specifier|private
specifier|final
name|CryptoProtocolVersion
name|version
decl_stmt|;
DECL|field|suite
specifier|private
specifier|final
name|CipherSuite
name|suite
decl_stmt|;
DECL|field|keyName
specifier|private
specifier|final
name|String
name|keyName
decl_stmt|;
DECL|method|BucketEncryptionKeyInfo ( CryptoProtocolVersion version, CipherSuite suite, String keyName)
specifier|public
name|BucketEncryptionKeyInfo
parameter_list|(
name|CryptoProtocolVersion
name|version
parameter_list|,
name|CipherSuite
name|suite
parameter_list|,
name|String
name|keyName
parameter_list|)
block|{
name|this
operator|.
name|version
operator|=
name|version
expr_stmt|;
name|this
operator|.
name|suite
operator|=
name|suite
expr_stmt|;
name|this
operator|.
name|keyName
operator|=
name|keyName
expr_stmt|;
block|}
DECL|method|getKeyName ()
specifier|public
name|String
name|getKeyName
parameter_list|()
block|{
return|return
name|keyName
return|;
block|}
DECL|method|getSuite ()
specifier|public
name|CipherSuite
name|getSuite
parameter_list|()
block|{
return|return
name|suite
return|;
block|}
DECL|method|getVersion ()
specifier|public
name|CryptoProtocolVersion
name|getVersion
parameter_list|()
block|{
return|return
name|version
return|;
block|}
comment|/**    * Builder for BucketEncryptionKeyInfo.    */
DECL|class|Builder
specifier|public
specifier|static
class|class
name|Builder
block|{
DECL|field|version
specifier|private
name|CryptoProtocolVersion
name|version
decl_stmt|;
DECL|field|suite
specifier|private
name|CipherSuite
name|suite
decl_stmt|;
DECL|field|keyName
specifier|private
name|String
name|keyName
decl_stmt|;
DECL|method|setKeyName (String name)
specifier|public
name|Builder
name|setKeyName
parameter_list|(
name|String
name|name
parameter_list|)
block|{
name|this
operator|.
name|keyName
operator|=
name|name
expr_stmt|;
return|return
name|this
return|;
block|}
DECL|method|setSuite (CipherSuite cs)
specifier|public
name|Builder
name|setSuite
parameter_list|(
name|CipherSuite
name|cs
parameter_list|)
block|{
name|this
operator|.
name|suite
operator|=
name|cs
expr_stmt|;
return|return
name|this
return|;
block|}
DECL|method|setVersion (CryptoProtocolVersion ver)
specifier|public
name|Builder
name|setVersion
parameter_list|(
name|CryptoProtocolVersion
name|ver
parameter_list|)
block|{
name|this
operator|.
name|version
operator|=
name|ver
expr_stmt|;
return|return
name|this
return|;
block|}
DECL|method|build ()
specifier|public
name|BucketEncryptionKeyInfo
name|build
parameter_list|()
block|{
return|return
operator|new
name|BucketEncryptionKeyInfo
argument_list|(
name|version
argument_list|,
name|suite
argument_list|,
name|keyName
argument_list|)
return|;
block|}
block|}
block|}
end_class

end_unit

