begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements.  See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership.  The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|org.apache.hadoop.hdfs.server.namenode
package|package
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hdfs
operator|.
name|server
operator|.
name|namenode
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|File
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|FileInputStream
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|BufferedInputStream
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|EOFException
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|DataInputStream
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hdfs
operator|.
name|protocol
operator|.
name|HdfsConstants
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|hdfs
operator|.
name|server
operator|.
name|common
operator|.
name|Storage
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|io
operator|.
name|IOUtils
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|annotations
operator|.
name|VisibleForTesting
import|;
end_import

begin_comment
comment|/**  * An implementation of the abstract class {@link EditLogInputStream}, which  * reads edits from a local file.  */
end_comment

begin_class
DECL|class|EditLogFileInputStream
specifier|public
class|class
name|EditLogFileInputStream
extends|extends
name|EditLogInputStream
block|{
DECL|field|file
specifier|private
specifier|final
name|File
name|file
decl_stmt|;
DECL|field|fStream
specifier|private
specifier|final
name|FileInputStream
name|fStream
decl_stmt|;
DECL|field|firstTxId
specifier|final
specifier|private
name|long
name|firstTxId
decl_stmt|;
DECL|field|lastTxId
specifier|final
specifier|private
name|long
name|lastTxId
decl_stmt|;
DECL|field|logVersion
specifier|private
specifier|final
name|int
name|logVersion
decl_stmt|;
DECL|field|reader
specifier|private
specifier|final
name|FSEditLogOp
operator|.
name|Reader
name|reader
decl_stmt|;
DECL|field|tracker
specifier|private
specifier|final
name|FSEditLogLoader
operator|.
name|PositionTrackingInputStream
name|tracker
decl_stmt|;
DECL|field|isInProgress
specifier|private
specifier|final
name|boolean
name|isInProgress
decl_stmt|;
comment|/**    * Open an EditLogInputStream for the given file.    * The file is pretransactional, so has no txids    * @param name filename to open    * @throws LogHeaderCorruptException if the header is either missing or    *         appears to be corrupt/truncated    * @throws IOException if an actual IO error occurs while reading the    *         header    */
DECL|method|EditLogFileInputStream (File name)
name|EditLogFileInputStream
parameter_list|(
name|File
name|name
parameter_list|)
throws|throws
name|LogHeaderCorruptException
throws|,
name|IOException
block|{
name|this
argument_list|(
name|name
argument_list|,
name|HdfsConstants
operator|.
name|INVALID_TXID
argument_list|,
name|HdfsConstants
operator|.
name|INVALID_TXID
argument_list|,
literal|false
argument_list|)
expr_stmt|;
block|}
comment|/**    * Open an EditLogInputStream for the given file.    * @param name filename to open    * @param firstTxId first transaction found in file    * @param lastTxId last transaction id found in file    * @throws LogHeaderCorruptException if the header is either missing or    *         appears to be corrupt/truncated    * @throws IOException if an actual IO error occurs while reading the    *         header    */
DECL|method|EditLogFileInputStream (File name, long firstTxId, long lastTxId, boolean isInProgress)
specifier|public
name|EditLogFileInputStream
parameter_list|(
name|File
name|name
parameter_list|,
name|long
name|firstTxId
parameter_list|,
name|long
name|lastTxId
parameter_list|,
name|boolean
name|isInProgress
parameter_list|)
throws|throws
name|LogHeaderCorruptException
throws|,
name|IOException
block|{
name|file
operator|=
name|name
expr_stmt|;
name|fStream
operator|=
operator|new
name|FileInputStream
argument_list|(
name|name
argument_list|)
expr_stmt|;
name|BufferedInputStream
name|bin
init|=
operator|new
name|BufferedInputStream
argument_list|(
name|fStream
argument_list|)
decl_stmt|;
name|tracker
operator|=
operator|new
name|FSEditLogLoader
operator|.
name|PositionTrackingInputStream
argument_list|(
name|bin
argument_list|)
expr_stmt|;
name|DataInputStream
name|in
init|=
operator|new
name|DataInputStream
argument_list|(
name|tracker
argument_list|)
decl_stmt|;
try|try
block|{
name|logVersion
operator|=
name|readLogVersion
argument_list|(
name|in
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|EOFException
name|eofe
parameter_list|)
block|{
throw|throw
operator|new
name|LogHeaderCorruptException
argument_list|(
literal|"No header found in log"
argument_list|)
throw|;
block|}
name|reader
operator|=
operator|new
name|FSEditLogOp
operator|.
name|Reader
argument_list|(
name|in
argument_list|,
name|logVersion
argument_list|)
expr_stmt|;
name|this
operator|.
name|firstTxId
operator|=
name|firstTxId
expr_stmt|;
name|this
operator|.
name|lastTxId
operator|=
name|lastTxId
expr_stmt|;
name|this
operator|.
name|isInProgress
operator|=
name|isInProgress
expr_stmt|;
block|}
annotation|@
name|Override
DECL|method|getFirstTxId ()
specifier|public
name|long
name|getFirstTxId
parameter_list|()
throws|throws
name|IOException
block|{
return|return
name|firstTxId
return|;
block|}
annotation|@
name|Override
DECL|method|getLastTxId ()
specifier|public
name|long
name|getLastTxId
parameter_list|()
throws|throws
name|IOException
block|{
return|return
name|lastTxId
return|;
block|}
annotation|@
name|Override
DECL|method|getName ()
specifier|public
name|String
name|getName
parameter_list|()
block|{
return|return
name|file
operator|.
name|getPath
argument_list|()
return|;
block|}
annotation|@
name|Override
DECL|method|nextOp ()
specifier|protected
name|FSEditLogOp
name|nextOp
parameter_list|()
throws|throws
name|IOException
block|{
name|FSEditLogOp
name|op
init|=
name|reader
operator|.
name|readOp
argument_list|(
literal|false
argument_list|)
decl_stmt|;
if|if
condition|(
operator|(
name|op
operator|!=
literal|null
operator|)
operator|&&
operator|(
name|op
operator|.
name|hasTransactionId
argument_list|()
operator|)
condition|)
block|{
name|long
name|txId
init|=
name|op
operator|.
name|getTransactionId
argument_list|()
decl_stmt|;
if|if
condition|(
operator|(
name|txId
operator|>=
name|lastTxId
operator|)
operator|&&
operator|(
name|lastTxId
operator|!=
name|HdfsConstants
operator|.
name|INVALID_TXID
operator|)
condition|)
block|{
comment|//
comment|// Sometimes, the NameNode crashes while it's writing to the
comment|// edit log.  In that case, you can end up with an unfinalized edit log
comment|// which has some garbage at the end.
comment|// JournalManager#recoverUnfinalizedSegments will finalize these
comment|// unfinished edit logs, giving them a defined final transaction
comment|// ID.  Then they will be renamed, so that any subsequent
comment|// readers will have this information.
comment|//
comment|// Since there may be garbage at the end of these "cleaned up"
comment|// logs, we want to be sure to skip it here if we've read everything
comment|// we were supposed to read out of the stream.
comment|// So we force an EOF on all subsequent reads.
comment|//
name|long
name|skipAmt
init|=
name|file
operator|.
name|length
argument_list|()
operator|-
name|tracker
operator|.
name|getPos
argument_list|()
decl_stmt|;
if|if
condition|(
name|skipAmt
operator|>
literal|0
condition|)
block|{
name|FSImage
operator|.
name|LOG
operator|.
name|warn
argument_list|(
literal|"skipping "
operator|+
name|skipAmt
operator|+
literal|" bytes at the end "
operator|+
literal|"of edit log  '"
operator|+
name|getName
argument_list|()
operator|+
literal|"': reached txid "
operator|+
name|txId
operator|+
literal|" out of "
operator|+
name|lastTxId
argument_list|)
expr_stmt|;
name|tracker
operator|.
name|skip
argument_list|(
name|skipAmt
argument_list|)
expr_stmt|;
block|}
block|}
block|}
return|return
name|op
return|;
block|}
annotation|@
name|Override
DECL|method|nextValidOp ()
specifier|protected
name|FSEditLogOp
name|nextValidOp
parameter_list|()
block|{
try|try
block|{
return|return
name|reader
operator|.
name|readOp
argument_list|(
literal|true
argument_list|)
return|;
block|}
catch|catch
parameter_list|(
name|IOException
name|e
parameter_list|)
block|{
return|return
literal|null
return|;
block|}
block|}
annotation|@
name|Override
DECL|method|getVersion ()
specifier|public
name|int
name|getVersion
parameter_list|()
throws|throws
name|IOException
block|{
return|return
name|logVersion
return|;
block|}
annotation|@
name|Override
DECL|method|getPosition ()
specifier|public
name|long
name|getPosition
parameter_list|()
block|{
return|return
name|tracker
operator|.
name|getPos
argument_list|()
return|;
block|}
annotation|@
name|Override
DECL|method|close ()
specifier|public
name|void
name|close
parameter_list|()
throws|throws
name|IOException
block|{
name|fStream
operator|.
name|close
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Override
DECL|method|length ()
specifier|public
name|long
name|length
parameter_list|()
throws|throws
name|IOException
block|{
comment|// file size + size of both buffers
return|return
name|file
operator|.
name|length
argument_list|()
return|;
block|}
annotation|@
name|Override
DECL|method|isInProgress ()
specifier|public
name|boolean
name|isInProgress
parameter_list|()
block|{
return|return
name|isInProgress
return|;
block|}
annotation|@
name|Override
DECL|method|toString ()
specifier|public
name|String
name|toString
parameter_list|()
block|{
return|return
name|getName
argument_list|()
return|;
block|}
DECL|method|validateEditLog (File file)
specifier|static
name|FSEditLogLoader
operator|.
name|EditLogValidation
name|validateEditLog
parameter_list|(
name|File
name|file
parameter_list|)
throws|throws
name|IOException
block|{
name|EditLogFileInputStream
name|in
decl_stmt|;
try|try
block|{
name|in
operator|=
operator|new
name|EditLogFileInputStream
argument_list|(
name|file
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|LogHeaderCorruptException
name|corrupt
parameter_list|)
block|{
comment|// If the header is malformed or the wrong value, this indicates a corruption
name|FSImage
operator|.
name|LOG
operator|.
name|warn
argument_list|(
literal|"Log at "
operator|+
name|file
operator|+
literal|" has no valid header"
argument_list|,
name|corrupt
argument_list|)
expr_stmt|;
return|return
operator|new
name|FSEditLogLoader
operator|.
name|EditLogValidation
argument_list|(
literal|0
argument_list|,
name|HdfsConstants
operator|.
name|INVALID_TXID
argument_list|,
name|HdfsConstants
operator|.
name|INVALID_TXID
argument_list|,
literal|true
argument_list|)
return|;
block|}
try|try
block|{
return|return
name|FSEditLogLoader
operator|.
name|validateEditLog
argument_list|(
name|in
argument_list|)
return|;
block|}
finally|finally
block|{
name|IOUtils
operator|.
name|closeStream
argument_list|(
name|in
argument_list|)
expr_stmt|;
block|}
block|}
comment|/**    * Read the header of fsedit log    * @param in fsedit stream    * @return the edit log version number    * @throws IOException if error occurs    */
annotation|@
name|VisibleForTesting
DECL|method|readLogVersion (DataInputStream in)
specifier|static
name|int
name|readLogVersion
parameter_list|(
name|DataInputStream
name|in
parameter_list|)
throws|throws
name|IOException
throws|,
name|LogHeaderCorruptException
block|{
name|int
name|logVersion
decl_stmt|;
try|try
block|{
name|logVersion
operator|=
name|in
operator|.
name|readInt
argument_list|()
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|EOFException
name|eofe
parameter_list|)
block|{
throw|throw
operator|new
name|LogHeaderCorruptException
argument_list|(
literal|"Reached EOF when reading log header"
argument_list|)
throw|;
block|}
if|if
condition|(
name|logVersion
argument_list|<
name|HdfsConstants
operator|.
name|LAYOUT_VERSION
operator|||
comment|// future version
name|logVersion
argument_list|>
name|Storage
operator|.
name|LAST_UPGRADABLE_LAYOUT_VERSION
condition|)
block|{
comment|// unsupported
throw|throw
operator|new
name|LogHeaderCorruptException
argument_list|(
literal|"Unexpected version of the file system log file: "
operator|+
name|logVersion
operator|+
literal|". Current version = "
operator|+
name|HdfsConstants
operator|.
name|LAYOUT_VERSION
operator|+
literal|"."
argument_list|)
throw|;
block|}
return|return
name|logVersion
return|;
block|}
comment|/**    * Exception indicating that the header of an edits log file is    * corrupted. This can be because the header is not present,    * or because the header data is invalid (eg claims to be    * over a newer version than the running NameNode)    */
DECL|class|LogHeaderCorruptException
specifier|static
class|class
name|LogHeaderCorruptException
extends|extends
name|IOException
block|{
DECL|field|serialVersionUID
specifier|private
specifier|static
specifier|final
name|long
name|serialVersionUID
init|=
literal|1L
decl_stmt|;
DECL|method|LogHeaderCorruptException (String msg)
specifier|private
name|LogHeaderCorruptException
parameter_list|(
name|String
name|msg
parameter_list|)
block|{
name|super
argument_list|(
name|msg
argument_list|)
expr_stmt|;
block|}
block|}
block|}
end_class

end_unit

