begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements.  See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership.  The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|org.apache.hadoop.mapred.pipes
package|package
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|mapred
operator|.
name|pipes
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|io
operator|.
name|FloatWritable
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|io
operator|.
name|NullWritable
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|io
operator|.
name|Text
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|io
operator|.
name|WritableUtils
import|;
end_import

begin_comment
comment|/*  Stub for  TestPipeApplication   test. This stub produced test data for main test. Main test  checks data  */
end_comment

begin_class
DECL|class|PipeApplicationRunnableStub
specifier|public
class|class
name|PipeApplicationRunnableStub
extends|extends
name|CommonStub
block|{
DECL|method|main (String[] args)
specifier|public
specifier|static
name|void
name|main
parameter_list|(
name|String
index|[]
name|args
parameter_list|)
block|{
name|PipeApplicationRunnableStub
name|client
init|=
operator|new
name|PipeApplicationRunnableStub
argument_list|()
decl_stmt|;
name|client
operator|.
name|binaryProtocolStub
argument_list|()
expr_stmt|;
block|}
DECL|method|binaryProtocolStub ()
specifier|public
name|void
name|binaryProtocolStub
parameter_list|()
block|{
try|try
block|{
name|initSoket
argument_list|()
expr_stmt|;
name|System
operator|.
name|out
operator|.
name|println
argument_list|(
literal|"start OK"
argument_list|)
expr_stmt|;
comment|// RUN_MAP.code
comment|// should be 3
name|int
name|answer
init|=
name|WritableUtils
operator|.
name|readVInt
argument_list|(
name|dataInput
argument_list|)
decl_stmt|;
name|System
operator|.
name|out
operator|.
name|println
argument_list|(
literal|"RunMap:"
operator|+
name|answer
argument_list|)
expr_stmt|;
name|TestPipeApplication
operator|.
name|FakeSplit
name|split
init|=
operator|new
name|TestPipeApplication
operator|.
name|FakeSplit
argument_list|()
decl_stmt|;
name|readObject
argument_list|(
name|split
argument_list|,
name|dataInput
argument_list|)
expr_stmt|;
name|WritableUtils
operator|.
name|readVInt
argument_list|(
name|dataInput
argument_list|)
expr_stmt|;
name|WritableUtils
operator|.
name|readVInt
argument_list|(
name|dataInput
argument_list|)
expr_stmt|;
comment|// end runMap
comment|// get InputTypes
name|WritableUtils
operator|.
name|readVInt
argument_list|(
name|dataInput
argument_list|)
expr_stmt|;
name|String
name|inText
init|=
name|Text
operator|.
name|readString
argument_list|(
name|dataInput
argument_list|)
decl_stmt|;
name|System
operator|.
name|out
operator|.
name|println
argument_list|(
literal|"Key class:"
operator|+
name|inText
argument_list|)
expr_stmt|;
name|inText
operator|=
name|Text
operator|.
name|readString
argument_list|(
name|dataInput
argument_list|)
expr_stmt|;
name|System
operator|.
name|out
operator|.
name|println
argument_list|(
literal|"Value class:"
operator|+
name|inText
argument_list|)
expr_stmt|;
annotation|@
name|SuppressWarnings
argument_list|(
literal|"unused"
argument_list|)
name|int
name|inCode
init|=
literal|0
decl_stmt|;
comment|// read all data from sender and write to output
while|while
condition|(
operator|(
name|inCode
operator|=
name|WritableUtils
operator|.
name|readVInt
argument_list|(
name|dataInput
argument_list|)
operator|)
operator|==
literal|4
condition|)
block|{
name|FloatWritable
name|key
init|=
operator|new
name|FloatWritable
argument_list|()
decl_stmt|;
name|NullWritable
name|value
init|=
name|NullWritable
operator|.
name|get
argument_list|()
decl_stmt|;
name|readObject
argument_list|(
name|key
argument_list|,
name|dataInput
argument_list|)
expr_stmt|;
name|System
operator|.
name|out
operator|.
name|println
argument_list|(
literal|"value:"
operator|+
name|key
operator|.
name|get
argument_list|()
argument_list|)
expr_stmt|;
name|readObject
argument_list|(
name|value
argument_list|,
name|dataInput
argument_list|)
expr_stmt|;
block|}
name|WritableUtils
operator|.
name|writeVInt
argument_list|(
name|dataOut
argument_list|,
literal|54
argument_list|)
expr_stmt|;
name|dataOut
operator|.
name|flush
argument_list|()
expr_stmt|;
name|dataOut
operator|.
name|close
argument_list|()
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|Exception
name|x
parameter_list|)
block|{
name|x
operator|.
name|printStackTrace
argument_list|()
expr_stmt|;
block|}
finally|finally
block|{
name|closeSoket
argument_list|()
expr_stmt|;
block|}
block|}
block|}
end_class

end_unit

