begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements.  See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership.  The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|org.apache.hadoop.yarn.service
package|package
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|yarn
operator|.
name|service
package|;
end_package

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|Lists
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|yarn
operator|.
name|service
operator|.
name|api
operator|.
name|records
operator|.
name|Component
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|yarn
operator|.
name|service
operator|.
name|api
operator|.
name|records
operator|.
name|ConfigFile
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|yarn
operator|.
name|service
operator|.
name|api
operator|.
name|records
operator|.
name|Configuration
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|hadoop
operator|.
name|yarn
operator|.
name|service
operator|.
name|api
operator|.
name|records
operator|.
name|Service
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Assert
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Test
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|*
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|junit
operator|.
name|Assert
operator|.
name|assertEquals
import|;
end_import

begin_comment
comment|/**  * Tests for {@link UpgradeComponentsFinder.DefaultUpgradeComponentsFinder}.  */
end_comment

begin_class
DECL|class|TestDefaultUpgradeComponentsFinder
specifier|public
class|class
name|TestDefaultUpgradeComponentsFinder
block|{
DECL|field|finder
specifier|private
name|UpgradeComponentsFinder
operator|.
name|DefaultUpgradeComponentsFinder
name|finder
init|=
operator|new
name|UpgradeComponentsFinder
operator|.
name|DefaultUpgradeComponentsFinder
argument_list|()
decl_stmt|;
annotation|@
name|Test
DECL|method|testServiceArtifactChange ()
specifier|public
name|void
name|testServiceArtifactChange
parameter_list|()
block|{
name|Service
name|currentDef
init|=
name|ServiceTestUtils
operator|.
name|createExampleApplication
argument_list|()
decl_stmt|;
name|Service
name|targetDef
init|=
name|ServiceTestUtils
operator|.
name|createExampleApplication
argument_list|()
decl_stmt|;
name|targetDef
operator|.
name|getComponents
argument_list|()
operator|.
name|forEach
argument_list|(
name|x
lambda|->
name|x
operator|.
name|setArtifact
argument_list|(
name|TestServiceManager
operator|.
name|createTestArtifact
argument_list|(
literal|"v1"
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"all components need upgrade"
argument_list|,
name|targetDef
operator|.
name|getComponents
argument_list|()
argument_list|,
name|finder
operator|.
name|findTargetComponentSpecs
argument_list|(
name|currentDef
argument_list|,
name|targetDef
argument_list|)
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
DECL|method|testServiceUpgradeWithNewComponentAddition ()
specifier|public
name|void
name|testServiceUpgradeWithNewComponentAddition
parameter_list|()
block|{
name|Service
name|currentDef
init|=
name|ServiceTestUtils
operator|.
name|createExampleApplication
argument_list|()
decl_stmt|;
name|Service
name|targetDef
init|=
name|ServiceTestUtils
operator|.
name|createExampleApplication
argument_list|()
decl_stmt|;
name|Iterator
argument_list|<
name|Component
argument_list|>
name|targetComponentsIter
init|=
name|targetDef
operator|.
name|getComponents
argument_list|()
operator|.
name|iterator
argument_list|()
decl_stmt|;
name|Component
name|firstComponent
init|=
name|targetComponentsIter
operator|.
name|next
argument_list|()
decl_stmt|;
name|firstComponent
operator|.
name|setName
argument_list|(
literal|"newComponentA"
argument_list|)
expr_stmt|;
try|try
block|{
name|finder
operator|.
name|findTargetComponentSpecs
argument_list|(
name|currentDef
argument_list|,
name|targetDef
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|fail
argument_list|(
literal|"Expected error since component does not exist in service "
operator|+
literal|"definition"
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|UnsupportedOperationException
name|usoe
parameter_list|)
block|{
name|assertEquals
argument_list|(
literal|"addition/deletion of components not supported by upgrade. Could "
operator|+
literal|"not find component newComponentA in current service "
operator|+
literal|"definition."
argument_list|,
name|usoe
operator|.
name|getMessage
argument_list|()
argument_list|)
expr_stmt|;
comment|//Expected
block|}
block|}
annotation|@
name|Test
DECL|method|testComponentArtifactChange ()
specifier|public
name|void
name|testComponentArtifactChange
parameter_list|()
block|{
name|Service
name|currentDef
init|=
name|TestServiceManager
operator|.
name|createBaseDef
argument_list|(
literal|"test"
argument_list|)
decl_stmt|;
name|Service
name|targetDef
init|=
name|TestServiceManager
operator|.
name|createBaseDef
argument_list|(
literal|"test"
argument_list|)
decl_stmt|;
name|targetDef
operator|.
name|getComponents
argument_list|()
operator|.
name|get
argument_list|(
literal|0
argument_list|)
operator|.
name|setArtifact
argument_list|(
name|TestServiceManager
operator|.
name|createTestArtifact
argument_list|(
literal|"v2"
argument_list|)
argument_list|)
expr_stmt|;
name|List
argument_list|<
name|Component
argument_list|>
name|expected
init|=
operator|new
name|ArrayList
argument_list|<>
argument_list|()
decl_stmt|;
name|expected
operator|.
name|add
argument_list|(
name|targetDef
operator|.
name|getComponents
argument_list|()
operator|.
name|get
argument_list|(
literal|0
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"single components needs upgrade"
argument_list|,
name|expected
argument_list|,
name|finder
operator|.
name|findTargetComponentSpecs
argument_list|(
name|currentDef
argument_list|,
name|targetDef
argument_list|)
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
DECL|method|testChangeInConfigFileProperty ()
specifier|public
name|void
name|testChangeInConfigFileProperty
parameter_list|()
block|{
name|ConfigFile
name|file
init|=
operator|new
name|ConfigFile
argument_list|()
operator|.
name|srcFile
argument_list|(
literal|"src"
argument_list|)
operator|.
name|destFile
argument_list|(
literal|"dest"
argument_list|)
operator|.
name|type
argument_list|(
name|ConfigFile
operator|.
name|TypeEnum
operator|.
name|HADOOP_XML
argument_list|)
decl_stmt|;
name|Map
argument_list|<
name|String
argument_list|,
name|String
argument_list|>
name|props
init|=
operator|new
name|HashMap
argument_list|<>
argument_list|()
decl_stmt|;
name|props
operator|.
name|put
argument_list|(
literal|"k1"
argument_list|,
literal|"v1"
argument_list|)
expr_stmt|;
name|file
operator|.
name|setProperties
argument_list|(
name|props
argument_list|)
expr_stmt|;
name|Configuration
name|conf
init|=
operator|new
name|Configuration
argument_list|()
operator|.
name|files
argument_list|(
name|Lists
operator|.
name|newArrayList
argument_list|(
name|file
argument_list|)
argument_list|)
decl_stmt|;
name|Service
name|currentDef
init|=
name|TestServiceManager
operator|.
name|createBaseDef
argument_list|(
literal|"test"
argument_list|)
decl_stmt|;
name|currentDef
operator|.
name|setConfiguration
argument_list|(
name|conf
argument_list|)
expr_stmt|;
comment|// new spec has changes in config file property
name|file
operator|=
operator|new
name|ConfigFile
argument_list|()
operator|.
name|srcFile
argument_list|(
literal|"src"
argument_list|)
operator|.
name|destFile
argument_list|(
literal|"dest"
argument_list|)
operator|.
name|type
argument_list|(
name|ConfigFile
operator|.
name|TypeEnum
operator|.
name|HADOOP_XML
argument_list|)
expr_stmt|;
name|Map
argument_list|<
name|String
argument_list|,
name|String
argument_list|>
name|changedProps
init|=
operator|new
name|HashMap
argument_list|<>
argument_list|()
decl_stmt|;
name|changedProps
operator|.
name|put
argument_list|(
literal|"k1"
argument_list|,
literal|"v2"
argument_list|)
expr_stmt|;
name|file
operator|.
name|setProperties
argument_list|(
name|changedProps
argument_list|)
expr_stmt|;
name|conf
operator|=
operator|new
name|Configuration
argument_list|()
operator|.
name|files
argument_list|(
name|Lists
operator|.
name|newArrayList
argument_list|(
name|file
argument_list|)
argument_list|)
expr_stmt|;
name|Service
name|targetDef
init|=
name|TestServiceManager
operator|.
name|createBaseDef
argument_list|(
literal|"test"
argument_list|)
decl_stmt|;
name|targetDef
operator|.
name|setConfiguration
argument_list|(
name|conf
argument_list|)
expr_stmt|;
name|List
argument_list|<
name|Component
argument_list|>
name|expected
init|=
operator|new
name|ArrayList
argument_list|<>
argument_list|()
decl_stmt|;
name|expected
operator|.
name|addAll
argument_list|(
name|targetDef
operator|.
name|getComponents
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"all components needs upgrade"
argument_list|,
name|expected
argument_list|,
name|finder
operator|.
name|findTargetComponentSpecs
argument_list|(
name|currentDef
argument_list|,
name|targetDef
argument_list|)
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

